# Config file for Air
[build]
bin = "main"
cmd = "go build -o ./bin/go-image-uploader cmd/main.go"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor"]
exclude_file = ["*_test.go"]
follow_symlink = true
full_bin = "APP_ENV=dev APP_USER=air ./bin/go-image-uploader"